# Generated by Django 3.0.3 on 2020-02-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='currentTemp',
        ),
        migrations.RemoveField(
            model_name='city',
            name='weatherType',
        ),
    ]
